---
- name: wait for connection
  become: false
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    timeout: 120
  connection: local

- name: check for python
  raw: which python
  register: whichpython
  changed_when: false

- name: debug python version
  ansible.builtin.debug:
    var: whichpython
  when: whichpython.stdout

- name: install python for ansible
  raw: rpm-ostree install python
  when: whichpython.failed
  register: pythoninstalled
  notify: "reboot-and-wait"

- name: wait for reboot
  become: false
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    delay: 10
    timeout: 300
  connection: local
  when: pythoninstalled.changed
